---
name: Module-Starter-Plugin-Template-TeTe
version: 0.06
author:
  - 'Kathryn Andersen (RUBYKAT) <perlkat AT katspace dot com>'
abstract: Module::Starter plugin for Text::Template templates
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  File::Spec: 0
  Module::Starter: 1.34
  Module::Starter::Plugin::Template: 0
  Text::Template: 1.44
build_requires:
  File::Path: 0
  Test::More: 0
provides:
  Module::Starter::Plugin::Template::TeTe:
    file: lib/Module/Starter/Plugin/Template/TeTe.pm
    version: 0.06
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
