#!/usr/bin/env perl

=head1 NAME

create_template_dir - create a template directory 

=head1 VERSION

This describes version B<0.04> of create_template_dir.

=cut

our $VERSION = '0.04';

=head1 SYNOPSIS

create_template_dir I<directory>

=head1 DESCRIPTION

This creates a template directory for the
Module::Starter::Plugin::Template::TeTe plugin for the Module::Starter
module, and populates it with the default templates.
Then the user can edit these to their heart's content, using the
created directory as their B<template_dir>.

=head1 AUTHOR

Kathryn Andersen (RUBYKAT), C<< <perlkat AT katspace dot com> >>

=head1 BUGS

Please report any bugs or feature requests to the author
at the above address.

=head1 COPYRIGHT AND LICENSE

Copyright 2004 Kathryn Andersen

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.

=cut

use strict;
use warnings;

use Module::Starter::Plugin::Template::TeTe;

my $template_dir = shift;

Module::Starter::Plugin::Template::TeTe->
	create_template_directory($template_dir);
